server.port=8081

# Application name
spring.application.name=auth-service

# Database configuration
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3308}/${DB_NAME:promo_engine}
spring.datasource.username=${DB_USER:promo}
spring.datasource.password=${DB_PASSWORD:promo}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Redis configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=0
spring.data.redis.password=
spring.data.redis.timeout=5000
spring.data.redis.retry-attempts=3000
spring.data.redis.retry-interval=1000
spring.data.redis.redisson.pool.connection-pool-size=16
spring.data.redis.redisson.pool.connection-minimum-idle-size=8
spring.data.redis.redisson.pool.connection-idle-timeout=10000

# Signature configuration
app.jwt.private-key=classpath:certs/private.pem
app.jwt.public-key=classpath:certs/public.pem
app.jwt.access-token-ttl=15m
app.jwt.refresh-token-ttl=7d


management.endpoints.web.exposure.include=health,info,metrics

# Logging configuration
#logging.level.org.springframework=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.com.promoengine=DEBUG